// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6twaj1zskYzIGMhxZtmpt5QVwcsbIQXU',
    appId: '1:521360573821:web:a9b73c54f0ccab67757814',
    messagingSenderId: '521360573821',
    projectId: 'foodapp-7d917',
    authDomain: 'foodapp-7d917.firebaseapp.com',
    storageBucket: 'foodapp-7d917.appspot.com',
    measurementId: 'G-3V12F0P0L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BdQ6kZPmbiNIkIfIhYhHzjc9l8rZ4Nk',
    appId: '1:521360573821:android:a25294f169f1d3b6757814',
    messagingSenderId: '521360573821',
    projectId: 'foodapp-7d917',
    storageBucket: 'foodapp-7d917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmDSyDQNONmPxAdb5RY6s_Ewt-yAl_tk',
    appId: '1:521360573821:ios:76ac44e4954f7bf7757814',
    messagingSenderId: '521360573821',
    projectId: 'foodapp-7d917',
    storageBucket: 'foodapp-7d917.appspot.com',
    iosClientId: '521360573821-8s417a6dc90eql8aduuega27hsbcu4ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmDSyDQNONmPxAdb5RY6s_Ewt-yAl_tk',
    appId: '1:521360573821:ios:76ac44e4954f7bf7757814',
    messagingSenderId: '521360573821',
    projectId: 'foodapp-7d917',
    storageBucket: 'foodapp-7d917.appspot.com',
    iosClientId: '521360573821-8s417a6dc90eql8aduuega27hsbcu4ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
